# Generated by Django 4.1.5 on 2023-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
