# Generated by Django 4.1.5 on 2023-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_video_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
    ]
