# Generated by Django 4.1.5 on 2023-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
