# Generated by Django 4.1.5 on 2023-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_video_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
