# Generated by Django 4.1.5 on 2023-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_video_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
    ]
