# Generated by Django 4.1.5 on 2023-06-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_video_audio_filename_alter_video_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='audio_filename',
            new_name='audio_fileName',
        ),
    ]
