# Generated by Django 4.1.5 on 2023-06-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_audio_filename_video_audio_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='timestamps',
            field=models.TextField(blank=True),
        ),
    ]
