# Generated by Django 4.1.5 on 2023-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_video_comments_video_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='timestamps',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
