# Generated by Django 4.1.5 on 2023-06-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_video_comments_alter_video_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='timestamps',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
                ('timestamps', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.video')),
            ],
        ),
    ]
