# Generated by Django 4.1.5 on 2023-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_video_comments_remove_video_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(),
        ),
    ]
