# Generated by Django 4.1.5 on 2023-06-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_video_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
